IMAGE_NAME = alpine
IMAGE_VERSION = 3.7
IMAGE_VERSION_ALIASES =	latest
IMAGE_TITLE = Alpine 3.7
IMAGE_DESCRIPTION = Alpine 3.7
IMAGE_SOURCE_URL = https://github.com/scaleway/image-alpine
IMAGE_VENDOR_URL = https://www.alpinelinux.org/
IMAGE_BOOTSCRIPT = mainline 4.4
IMAGE_BASE_FLAVORS = common openrc docker-based
