#!/usr/bin/env ash

arch_name=$(uname -m)
case "$arch_name" in
    "aarch64")
        arch_name="arm64"
        ;;
    "amd64")
        arch_name="x86_64"
        ;;
esac

grub-install --target=${arch_name}-efi --bootloader-id=grub --removable \
    --recheck --efi-dir=/boot/efi

# needed by 10_linux otherwise no modules will be specified
# cannot set this in /etc/default/grub :(
export modules="sd-mod,ext4"
grub-mkconfig -o /boot/grub/grub.cfg

# create mount point for the ESP
mkdir -p /boot/efi
